### PR TITLE
updated photos

### PR DESCRIPTION
**Pull request by uzska**

### CODE REVIEW

**Comment by Z2h-A6n** [comment]
Thanks, looks good. A couple of notes:

- The people within each section should be in alphabetical order by last name. I'll merge this and then make a commit to reorder everything before updating  the server.
- It's good (at least in principle) to make the commit messages a bit more descriptive.

**Comment by Z2h-A6n** [comment]
A few more notes:
- I commented-out Benjamin's picture for now. I don't think the intention of the "Frequent Visitors" section is for long-term collaborators who visit on a regular basis. I'll ask Martin if and where he wants Benjamin's photo on the site.
- All the site files use tab characters, not spaces for indentation. This doesn't affect how things look in a web browser, but since there are several different standards for how many spaces to use to render a tab character, it can make things pretty messy in a text editor to have a mix of tabs and spaces.

**Comment by Z2h-A6n** [comment]
One more thing: why did you add `style="object-position: 50% bottom"` to the `` for Nikolaos? It doesn't seem to change anything if I remove it. If this is something we should add to all of the photos, we should add it to the `#person img` definition in `style.css` to keep things organized.

**Comment by uzska** [comment]
Photos weren't as uniform as I thought, so I tried to crop the each photo individually using css, and couldn't get it right. I guess I forgot to get rid of the style tag. I ended up cropping the jpgs manually, then had them stretched out to be more or less the same size.

No reason for spaces. I guess I forgot to keep using tabs while editing.

**Pull request merged**
